// Generated by ts-to-zod
import { z } from "zod";

export const calendarFeedsIdSchema = z.string().and(
  z.object({
    __brand: z.literal("public.calendar_feeds"),
  }),
);

const userIdSchema = z.any();

export const calendarFeedsSchema = z.object({
  id: calendarFeedsIdSchema,
  user_id: userIdSchema,
  name: z.string(),
  ics_url: z.string(),
  color: z.string().nullable(),
  is_enabled: z.boolean(),
  created_at: z.date(),
  updated_at: z.date(),
});

export const calendarFeedsInitializerSchema = z.object({
  id: calendarFeedsIdSchema.optional(),
  user_id: userIdSchema,
  name: z.string(),
  ics_url: z.string(),
  color: z.string().optional().nullable(),
  is_enabled: z.boolean().optional(),
  created_at: z.date().optional(),
  updated_at: z.date().optional(),
});

export const calendarFeedsMutatorSchema = z.object({
  id: calendarFeedsIdSchema.optional(),
  user_id: userIdSchema.optional(),
  name: z.string().optional(),
  ics_url: z.string().optional(),
  color: z.string().optional().nullable(),
  is_enabled: z.boolean().optional(),
  created_at: z.date().optional(),
  updated_at: z.date().optional(),
});

export type CalendarFeeds = z.infer<typeof calendarFeedsSchema>;
export type CalendarFeedsInitializer = z.infer<
  typeof calendarFeedsInitializerSchema
>;
export type CalendarFeedsMutator = z.infer<typeof calendarFeedsMutatorSchema>;
