// Generated by ts-to-zod
import { z } from "zod";

export const plannedWorkoutsIdSchema = z.string().and(
  z.object({
    __brand: z.literal("public.planned_workouts"),
  }),
);

const userIdSchema = z.any();

const workoutPresetsIdSchema = z.any();

const exercisesIdSchema = z.any();

const exercisePresetEntriesIdSchema = z.any();

const workoutPlanTemplatesIdSchema = z.any();

const workoutPlanTemplateAssignmentsIdSchema = z.any();

export const plannedWorkoutsSchema = z.object({
  id: plannedWorkoutsIdSchema,
  user_id: userIdSchema,
  planned_date: z.date(),
  planned_time: z.string().nullable(),
  duration_estimate_minutes: z.number().nullable(),
  title: z.string(),
  workout_preset_id: workoutPresetsIdSchema.nullable(),
  exercise_id: exercisesIdSchema.nullable(),
  workout_type: z.string().nullable(),
  notes: z.string().nullable(),
  status: z.string(),
  started_at: z.date().nullable(),
  completed_at: z.date().nullable(),
  completed_session_id: exercisePresetEntriesIdSchema.nullable(),
  origin: z.string(),
  template_id: workoutPlanTemplatesIdSchema.nullable(),
  assignment_id: workoutPlanTemplateAssignmentsIdSchema.nullable(),
  generated_for_date: z.date().nullable(),
  slot: z.number().nullable(),
  user_modified: z.boolean(),
  dismissed_at: z.date().nullable(),
  created_at: z.date(),
  updated_at: z.date(),
});

export const plannedWorkoutsInitializerSchema = z.object({
  id: plannedWorkoutsIdSchema.optional(),
  user_id: userIdSchema,
  planned_date: z.date(),
  planned_time: z.string().optional().nullable(),
  duration_estimate_minutes: z.number().optional().nullable(),
  title: z.string(),
  workout_preset_id: workoutPresetsIdSchema.optional().nullable(),
  exercise_id: exercisesIdSchema.optional().nullable(),
  workout_type: z.string().optional().nullable(),
  notes: z.string().optional().nullable(),
  status: z.string().optional(),
  started_at: z.date().optional().nullable(),
  completed_at: z.date().optional().nullable(),
  completed_session_id: exercisePresetEntriesIdSchema.optional().nullable(),
  origin: z.string().optional(),
  template_id: workoutPlanTemplatesIdSchema.optional().nullable(),
  assignment_id: workoutPlanTemplateAssignmentsIdSchema.optional().nullable(),
  generated_for_date: z.date().optional().nullable(),
  slot: z.number().optional().nullable(),
  user_modified: z.boolean().optional(),
  dismissed_at: z.date().optional().nullable(),
  created_at: z.date().optional(),
  updated_at: z.date().optional(),
});

export const plannedWorkoutsMutatorSchema = z.object({
  id: plannedWorkoutsIdSchema.optional(),
  user_id: userIdSchema.optional(),
  planned_date: z.date().optional(),
  planned_time: z.string().optional().nullable(),
  duration_estimate_minutes: z.number().optional().nullable(),
  title: z.string().optional(),
  workout_preset_id: workoutPresetsIdSchema.optional().nullable(),
  exercise_id: exercisesIdSchema.optional().nullable(),
  workout_type: z.string().optional().nullable(),
  notes: z.string().optional().nullable(),
  status: z.string().optional(),
  started_at: z.date().optional().nullable(),
  completed_at: z.date().optional().nullable(),
  completed_session_id: exercisePresetEntriesIdSchema.optional().nullable(),
  origin: z.string().optional(),
  template_id: workoutPlanTemplatesIdSchema.optional().nullable(),
  assignment_id: workoutPlanTemplateAssignmentsIdSchema.optional().nullable(),
  generated_for_date: z.date().optional().nullable(),
  slot: z.number().optional().nullable(),
  user_modified: z.boolean().optional(),
  dismissed_at: z.date().optional().nullable(),
  created_at: z.date().optional(),
  updated_at: z.date().optional(),
});

export type PlannedWorkouts = z.infer<typeof plannedWorkoutsSchema>;
export type PlannedWorkoutsInitializer = z.infer<
  typeof plannedWorkoutsInitializerSchema
>;
export type PlannedWorkoutsMutator = z.infer<
  typeof plannedWorkoutsMutatorSchema
>;
